"""
MedSimplify — Additional Synthetic Training Data
High-quality Complex→Easy Read pairs for the specific document types we target.
These are the most important training examples — they define the output style.
"""

ADDITIONAL_SYNTHETIC_PAIRS = [
    {
        "instruction": "Transform this medical test result letter into Easy Read format. Use short sentences, emoji icons, bullet points for actions, urgency markers.",
        "input": "Dear Mr. Thompson, I am writing to confirm the results of your colonoscopy performed on 12/03/2026. During the procedure, two sessile polyps were identified in the ascending colon, measuring 8mm and 12mm respectively. Both were removed via polypectomy and sent for histological analysis. The histology results confirm tubular adenomas with low-grade dysplasia. While these are not cancerous, they represent a pre-cancerous condition that requires surveillance. I would recommend a repeat colonoscopy in 3 years. Please also ensure you attend your routine bowel cancer screening when invited. If you experience any rectal bleeding, abdominal pain, or significant change in bowel habits before your next appointment, please contact us urgently.",
        "output": "📋 About your test (colonoscopy)\n\nThe doctor looked inside your bowel.\nThey found 2 small lumps (called polyps).\nThey took the lumps out during the test.\n\n✅ Good news:\nThe lumps are NOT cancer.\n\n⚠️ But:\nThey could become cancer in the future.\nSo you need another test in 3 years.\n\n📅 What you need to do:\n• Have another colonoscopy in 3 years (2029)\n• Go to bowel cancer screening when you get invited\n\n🚨 Call the doctor NOW if you have:\n• Blood when you go to the toilet\n• Pain in your tummy\n• Big changes in how you go to the toilet"
    },
    {
        "instruction": "Transform this mental health referral letter into Easy Read format. Use short sentences, emoji icons, bullet points for actions.",
        "input": "Dear Patient, Following your GP's referral dated 28/02/2026, we are pleased to confirm that you have been accepted onto the Improving Access to Psychological Therapies (IAPT) programme. Your initial assessment appointment has been scheduled for 15/04/2026 at 14:30 at the Community Mental Health Centre, 42 Park Road. The appointment will last approximately 50 minutes. Please arrive 10 minutes early to complete registration paperwork. If you are unable to attend, please give us at least 48 hours notice by calling 0800 123 4567. Please note that two missed appointments without notice will result in discharge from the service. You may wish to bring a trusted person for support.",
        "output": "📋 Good news about your mental health support\n\n✅ You have been accepted for talking therapy.\n\n📅 Your first appointment:\n• Date: April 15, 2026\n• Time: 2:30 PM\n• Where: Community Mental Health Centre, 42 Park Road\n• How long: about 50 minutes\n\n✅ What to do:\n• Get there 10 minutes early\n• Fill in some forms when you arrive\n• You can bring someone with you for support\n\n📞 If you can't go:\n• Call: 0800 123 4567\n• Call at least 2 days before\n\n⚠️ Important:\nIf you miss 2 appointments without telling them,\nthey will stop your therapy."
    },
    {
        "instruction": "Transform this benefits sanctions letter into Easy Read format. Use short sentences, emoji icons, bullet points for actions.",
        "input": "NOTIFICATION OF SANCTION: We are writing to inform you that a sanction has been applied to your Universal Credit payments with effect from 01/04/2026. The reason for this sanction is: failure to attend a mandatory Work Capability Assessment on 15/03/2026 without providing good cause within 5 working days. During the sanction period, your standard allowance will be reduced by £14.35 per day for a period of 91 days. Your housing element will not be affected. If you believe you had good cause for missing the appointment, you can request a Mandatory Reconsideration within one calendar month. You can also apply for a hardship payment if you cannot meet your basic needs. Contact your work coach or call the Universal Credit helpline on 0800 328 5644.",
        "output": "🔴 IMPORTANT — Your money has been cut\n\nYour Universal Credit has been reduced.\n\n📋 Why:\nYou missed an appointment on March 15.\nYou did not tell them why within 5 days.\n\n💰 How much less:\n• You will get £14.35 LESS every day\n• This lasts for 91 days\n• Your rent money is NOT affected\n\n✋ If you had a good reason for missing it:\n• You can ask them to change this decision\n• You must do this within 1 month\n• Call: 0800 328 5644\n\n⚠️ If you can't afford food or bills:\n• Ask for a \"hardship payment\"\n• Call your work coach\n• Or call: 0800 328 5644\n\n📞 Call NOW: 0800 328 5644"
    },
    {
        "instruction": "Transform this dental appointment letter into Easy Read format. Use short sentences, emoji icons, bullet points.",
        "input": "Dear Patient, Further to your recent dental examination, I am referring you for extraction of your lower right wisdom tooth (tooth 48) under local anaesthetic. The referral has been made to the Oral Surgery department at [Hospital Name]. You should expect to receive an appointment within 18 weeks. The procedure involves administration of local anaesthetic, elevation and extraction of the tooth, and placement of sutures which will dissolve in 7-10 days. Post-operative complications may include: swelling (2-3 days), restricted mouth opening (trismus), dry socket, and temporary numbness of the lower lip (paraesthesia). You should take ibuprofen 400mg every 6 hours for pain, and rinse with warm salt water after 24 hours. Avoid smoking for 48 hours post-extraction.",
        "output": "🦷 About your tooth\n\nYou need to have a wisdom tooth taken out.\nIt is the back tooth on your lower right side.\n\n📅 What happens next:\n• You will get a hospital appointment\n• This might take up to 18 weeks\n• They will numb your mouth (you won't feel pain)\n• They will take the tooth out\n• They will put stitches in (these dissolve on their own)\n\n⚠️ After the tooth is taken out:\n• Your face might swell for 2-3 days\n• Your mouth might not open fully\n• Your lip might feel numb for a while\n\n💊 Pain relief:\n• Take ibuprofen (400mg) every 6 hours\n• After 24 hours: rinse your mouth with warm salty water\n\n🚫 Do NOT:\n• Smoke for 2 days after"
    },
    {
        "instruction": "Transform this energy bill warning into Easy Read format. Use short sentences, emoji icons, bullet points.",
        "input": "DISCONNECTION WARNING: Account No: EL-2024-88714. Despite our previous correspondence dated 15/01/2026 and 28/02/2026, your electricity account remains in arrears of £847.23. If payment is not received within 28 days of this notice, we will apply to install a prepayment meter at your property. If access is not provided voluntarily, we may seek a warrant from a magistrate to gain access. A prepayment meter will be set to recover the debt at a rate of £3.80 per day in addition to your ongoing usage charges. If you are experiencing financial difficulty, please contact us on 0800 111 222 to discuss payment options including repayment plans, hardship funds, and Priority Services Register eligibility.",
        "output": "🔴 WARNING — Your electricity might be cut off\n\nYou owe £847.23 for electricity.\nYou have not paid.\n\n⏰ You have 28 days to pay.\n\n⚠️ If you don't pay in 28 days:\n• They will change your meter\n• The new meter needs money put in before it works\n• They will take £3.80 every day for what you owe\n• They can get permission to enter your home\n\n📞 If you can't afford to pay:\nCall them NOW: 0800 111 222\nThey can help you:\n• Make a payment plan (pay a little each week)\n• See if you can get help with money\n• Put you on priority support if you're vulnerable\n\n✅ What to do RIGHT NOW:\n• Call 0800 111 222 today\n• Don't ignore this letter\n• They WILL help if you ask"
    },
    {
        "instruction": "Transform this immigration letter into Easy Read format. Use short sentences, emoji icons, bullet points.",
        "input": "HOME OFFICE DECISION: Reference: VAR/2026/012345. We have considered your application for Leave to Remain under Appendix EU of the Immigration Rules. We regret to inform you that your application has been refused. The reason for this decision is: you have failed to provide sufficient evidence of continuous residence in the United Kingdom for a period of five years ending on 31 December 2020. The evidence provided demonstrates residence from June 2017 to December 2020, which constitutes 3 years and 6 months. You have the right to appeal this decision to the First-tier Tribunal within 14 days of receiving this letter. An appeal form (IAFT-5) is enclosed. You may also seek free legal advice from the EUSS Help Centre on 0300 123 7379.",
        "output": "🔴 IMPORTANT — About your right to stay in the UK\n\n❌ Decision:\nThe Home Office said NO to your application.\nYou asked to stay in the UK. They said no.\n\n📋 Why they said no:\n• You need to show you lived in the UK for 5 years\n• You only showed 3 years and 6 months\n• They need proof from 2015 to 2020\n• You only gave proof from 2017 to 2020\n\n✋ You can FIGHT this decision:\n• You can appeal (ask a judge to look again)\n• You MUST do this within 14 DAYS\n• Fill in the form that came with this letter (IAFT-5)\n\n📞 Get FREE help NOW:\n• Call: 0300 123 7379 (free)\n• They speak many languages\n• They can help you appeal\n\n⏰ DEADLINE: 14 days from today\nDo NOT wait. Call for help TODAY."
    },
    {
        "instruction": "Transform this school SEND decision letter into Easy Read format. Use short sentences, emoji icons, bullet points.",
        "input": "Dear Parent/Carer, Following the statutory assessment of your child's Special Educational Needs, we have decided to issue an Education, Health and Care Plan (EHCP). The draft EHCP is enclosed for your review. You have 15 calendar days from the date of this letter to provide comments on the draft, including your preference of educational placement. If you disagree with any aspect of the plan, you may request mediation through the Regional Mediation Service or lodge an appeal with the Special Educational Needs and Disability Tribunal (SENDIST) within 2 months. The local authority must issue the final EHCP within 20 weeks of the initial request for assessment. Your child's Named Officer is Sarah Williams (sarah.williams@council.gov.uk, 01234 567890).",
        "output": "✅ Good news about your child's support at school\n\nYour child WILL get an EHCP.\nThis means they will get extra help.\n\n📋 The plan:\nA plan for your child's help is with this letter.\nPlease read it.\n\n📅 What you need to do:\n• Read the plan\n• Tell them if anything is wrong\n• Say which school you want for your child\n• Do this within 15 days\n\n✋ If you disagree with the plan:\n• You can ask for mediation (someone helps you talk to the council)\n• OR you can appeal to a tribunal (a judge decides)\n• You have 2 months to appeal\n\n📞 Your contact person:\n• Name: Sarah Williams\n• Email: sarah.williams@council.gov.uk\n• Phone: 01234 567890\n\n⏰ Deadline to reply: 15 days from today"
    },
    {
        "instruction": "Transform this DWP fitness for work letter into Easy Read format. Use short sentences, emoji icons, bullet points.",
        "input": "WORK CAPABILITY ASSESSMENT OUTCOME: Following your Work Capability Assessment conducted on 22/02/2026, the Decision Maker has determined that you have Limited Capability for Work but do NOT have Limited Capability for Work-Related Activity. This means you will be placed in the Work-Related Activity Group (WRAG). You are required to attend Work-Focused Interviews with your Work Coach and undertake reasonable steps towards preparing for work. Failure to attend scheduled appointments or comply with your Claimant Commitment may result in a sanction being applied to your benefits. If you disagree with this decision, you can request a Mandatory Reconsideration within one calendar month. You should continue to provide fit notes from your GP.",
        "output": "📋 About your work assessment\n\n✅ They agree you are too unwell to work right now.\n\n⚠️ But:\nThey think you can get ready for work in the future.\nThis means you must do some things to prepare.\n\n📅 What you must do:\n• Go to meetings with your Work Coach\n• Do what it says in your plan\n• Keep getting sick notes from your doctor\n\n⚠️ If you don't go to meetings:\nThey might cut your money.\n\n✋ If you disagree:\n• Maybe you think you can't prepare for work at all\n• You can ask them to look at this again\n• You must do this within 1 month\n\n📞 Need help?\n• Call Citizens Advice: 0800 144 8848\n• They can help you challenge this for free"
    }
]

if __name__ == "__main__":
    import json
    from pathlib import Path

    output = Path("data/processed/synthetic_extra.jsonl")
    output.parent.mkdir(parents=True, exist_ok=True)

    with open(output, "w", encoding="utf-8") as f:
        for pair in ADDITIONAL_SYNTHETIC_PAIRS:
            f.write(json.dumps(pair, ensure_ascii=False) + "\n")
            # Also add variation with different instruction
            variation = {
                "instruction": "Convert this complex document to Easy Read format suitable for people with learning disabilities or low literacy. Maximum 10 words per sentence, use emoji markers, create action checklist at the end.",
                "input": pair["input"],
                "output": pair["output"]
            }
            f.write(json.dumps(variation, ensure_ascii=False) + "\n")

    print(f"Saved {len(ADDITIONAL_SYNTHETIC_PAIRS) * 2} additional pairs to {output}")
